.TH NINVADERS 6 "November 3, 2022"
.SH NAME
nInvaders \- Space Invaders in the terminal
.SH SYNOPSIS
.B nInvaders
[
.B \-l
level ]
.SH DESCRIPTION
Hello and welcome to nInvaders! Right now you are earth's only hope to save it from alien invaders from space. Make your job, and make it good, mankind believes in you...
.B nInvaders
.SH UPSTREAM URL
https://github.com/TheZ3ro/ninvaders
